[versions]

agp = "7.3.1"
gms = "4.3.14"
material = "1.6.1"
core = "1.6.0"

androidx-lifecycle = "2.5.1"
androidx-navigation = "2.5.2"
view-binding = "1.5.6"

hilt = "2.44"

kotlin = "1.7.0"
kotlin-serialization = "1.3.3"
kotlin-datetime = "0.4.0"
livedata-ktx = "2.5.1"
desugaring = "1.1.5"

timber = "5.0.1"
retrofit = "2.9.0"
chucker = "3.5.2"
lottie = "3.4.0"
glide = "4.14.2"

[libraries]

material = { module = "com.google.android.material:material", version.ref = "material" }
livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "livedata-ktx" }
core = { module = "androidx.core:core", version.ref = "core" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }

kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime" }
desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

view-binding = { module = "com.github.kirich1409:viewbindingpropertydelegate-noreflection", version.ref = "view-binding" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-release = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

[plugins]
android-app = { id = "com.android.application", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }